### PR TITLE
LOVE 1577- Added ACCEPT_EULA environment variable, and CFN parameter

### PR DESCRIPTION
**Pull request by spaliwal-xl**
This PR has two scenarios for testing:

AcceptEula = yes is a mandatory parameter in both the scenarios.

1. **Quick start if you have a license:** - use below AcceptEula, XLDeployLicense, and XLReleaseLicense parameter values in [taskcat.yml](https://github.com/xebialabs/quickstart-xebialabs-devops-platform/blob/LOVE-1577/ci/taskcat.yml) file

        AcceptEula: 'yes'
        XLDeployLicense: BASE64
        XLReleaseLicense: BASE64

2. **Quick start if you do not have a license:** - use below AcceptEula, XLDeployLicense, and XLReleaseLicense parameter values in [taskcat.yml](https://github.com/xebialabs/quickstart-xebialabs-devops-platform/blob/LOVE-1577/ci/taskcat.yml) file

       AcceptEula: 'yes'
       XLDeployLicense: trial
       XLReleaseLicense: trial

### CODE REVIEW

**Comment by dllz** [comment]
Running the taskcat tests for this pr brings this failure. 

```
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec                        [INFO   ] : ┣ region: ap-south-1                                               [INFO   ] : ┗ status: CREATE_FAILED                                            
[INFO   ] : Collecting CloudFormation Logs
[INFO   ] : Collecting logs for tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec
[INFO   ] : 	 |StackName: tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec
[INFO   ] : 	 |Region: ap-south-1
[INFO   ] : 	 |Logging to: /home/daniel/Documents/Xebialabs/quickstart-xebialabs-devops-platform/taskcat_outputs/tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec-ap-south-1-cfnlogs.txt
[INFO   ] : 	 |Tested on: Friday, 24. April 2020 10:08AM
[INFO   ] : ------------------------------------------------------------------------------------------
[INFO   ] : ResourceStatusReason: 
[INFO   ] : The following resource(s) failed to create: [VPCStack].
[INFO   ] : ==========================================================================================
[INFO   ] : Reporting on arn:aws:cloudformation:ap-south-1:932770550094:stack/tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec/ac770800-8602-11ea-81d6-0603bc2e8e1c
[INFO   ] : Deleting stack: arn:aws:cloudformation:ap-south-1:932770550094:stack/tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec/ac770800-8602-11ea-81d6-0603bc2e8e1c
[INFO   ] : ┏ stack Ⓜ tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec                        [INFO   ] : ┣ region: ap-south-1                                               [INFO   ] : ┗ status: DELETE_COMPLETE                                          
[ERROR  ] : One or more stacks failed tests: {'arn:aws:cloudformation:ap-south-1:932770550094:stack/tCaT-quickstart-xebialabs-devops-platform-quickstart-xebialabs-devops-platform1-49541f6296c24de19ccc21c33bba4cec/ac770800-8602-11ea-81d6-0603bc2e8e1c': 'The following resource(s) failed to create: [VPCStack]. '}
```
Please get the tests working and tag me to review.

**Comment by spaliwal-xl** [comment]
@dllz Clone LOVE-1577 branch on your local system using below command:
**git clone -b LOVE-1577 --recurse-submodules git@github.com:xebialabs/quickstart-xebialabs-devops-platform.git**

Edit taskcat.yml file with actual-license-string instead of BASE64

Command to run a stack:
**taskcat test run -i ci/taskcat.yml -n**

After this, if you still hit any error then please let me know.

**Comment by dllz** [comment]
Hi @spaliwal-xl So recloning it as provided worked. I did not have to change the license string in order to have successful tests. 

I would advise maybe updating the read me with the specific cloning instructions, you can use this PR for that as well if you just edit the Readme.

**Comment by spaliwal-xl** [comment]
Hi @dllz, I have updated README.md file with accurate git clone command in this PR

**Comment by dllz** [comment]
@spaliwal-xl Can you please put it at the top so its the first thing users see when they come here.

**Comment by spaliwal-xl** [comment]
> @spaliwal-xl Can you please put it at the top so its the first thing users see when they come here.

@dllz Done

**Comment by dllz** [comment]
@spaliwal-xl perfect, feel free to merge

**Comment by spaliwal-xl** [comment]
> @spaliwal-xl perfect, feel free to merge

@dllz Please approve the PR - https://github.com/xebialabs/quickstart-xebialabs-devops-platform/pull/9/files so that I can merge it

**Review by dllz — APPROVED** [review]

**Pull request merged**
